name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release --verbose
    - name: Move linutil binary
      run: mv target/release/linutil linutil
    - name: Replace linutil binary
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Replace linutil binary"
        file_pattern: ./linutil
        commit_options: "--allow-empty --no-verify"